version: "2"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb
      - MEMCACHEDCLOUD_SERVERS=memcached
    depends_on:
      - memcached
      - mongodb
  memcached:
    image: "memcached:latest"
    ports:
      - "11211:11211"
  mongodb:
    image: "mongo:3.6.17"
    ports:
      - "27017:27017"
