version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: build and run tests
          command: |
            mkdir ~/persistence
            docker-compsoe up -d
            docker-compose run app bundle exec rspec spec --format progress
